### ISSUE TITLE
allow functions as value in subdomains config

### ISSUE THREAD

**Issue by jfgodoy** [ksmithbaylor/node-subdomain-router#2]
what do you think of allow pass a function in the value of subdomains. This will allow to send custom messages or redirects.

```
var proxy = require('subdomain-router');

function redirect(req, res) {
  res.writeHead(302, {'Location': 'https://example.com'});
  res.end();
}

// Assuming 'example.com' and '*.example.com' point to this computer
proxy({
  host: 'example.com',
  subdomains: {
    '': 10000,             // 'example.com'             <=> localhost:10000
    www: 10000,            // 'www.example.com'         <=> localhost:10000
    blog: redirect
  }
}).listen(80);
```

I can make a pull request if you liked.

**Comment by ksmithbaylor** [comment]
Sorry it took so long to get back to you; I've been on vacation.

I don't know if that would be a good idea. For this use case, it might be better to do something like this:

``` javascript
var http = require('http');
var proxy = require('subdomain-router');

http.createServer(function (req, res) {
  res.writeHead(302, {'Location': 'https://example.com'});
  res.end();
}).listen(10001);

// Assuming 'example.com' and '*.example.com' point to this computer
proxy({
  host: 'example.com',
  subdomains: {
    '': 10000,             // 'example.com'             <=> localhost:10000
    www: 10000,            // 'www.example.com'         <=> localhost:10000
    blog: 10001
  }
}).listen(80);
```

It would certainly be doable to allow functions to be passed in the `subdomains` object, but this would be adding code/api complexity for no purpose other than an arguably cleaner syntax. This would also have to assume that the function should be treated as input to an `http` server. What if the user wanted to instead create a raw TCP server using the `net` module (which doesn't take `req` and `res` as arguments)? No, I think providing a low-level primitive like a port number is much more simple and useful.

I appreciate your input though! Let me know if you think of any other features that may be useful :)

**Comment by jfgodoy** [comment]
it's ok. :)
