### ISSUE TITLE
propagate request cancellation

### ISSUE THREAD

**Issue by jfgodoy** [ksmithbaylor/node-subdomain-router#3]
If an user cancel a pending request, the proxy do not notifies the target server about  the cancellation.

According the [node documentation](https://nodejs.org/api/http.html#http_event_close_1) the event `close` on the response is emitted when the the connection was terminate before response.end(), so  the propagation can be implemented with this:

```
res.on('close', function() {
   proxyRequest.abort();
});
```

I don't know if  there some other details that need to be considered, but this works for me.

**Comment by ksmithbaylor** [comment]
I like it! Would you mind making a pull request and I will merge it in?
