### ISSUE TITLE
Question: is possible to redirect a request to different hosts?

### ISSUE THREAD

**Issue by ferreiro** [ksmithbaylor/node-subdomain-router#6]
Hello! I'm using your module for redirecting requests for my API (port 5000) and Application (port 4000). And it works pretty well with heroku.

My question is if I can redirect a request to a different host? For example, if the user accesses to 'www', redirects to webpage (hosted in github). 

If not, is there any other module/technology I can use for this purpose?

Thanks in advance.
jorge

**Comment by ksmithbaylor** [comment]
Hey! Sorry it's taken me so long to reply to this, for some reason I just noticed it today. That functionality is not currently in this module, but I have had luck in the past doing similar things with [http-proxy](https://github.com/nodejitsu/node-http-proxy)!

**Comment by ksmithbaylor** [comment]
But it actually might be easier to do what you're suggesting using DNS. Depending on how you have it set up, you could redirect `www.` to your GitHub Pages URL ([instructions here](https://help.github.com/articles/using-a-custom-domain-with-github-pages/))

I'm going to go ahead and close this issue now. Feel free to reply if you have anything else.
